import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcryptjs";
import { computeTier, computeTotalScore } from "../src/evaluation/scoring";

// Seed de démo pour Groupe/Formateur/Apprenant — mirrors the exact 6 groupes
// / 30 apprenants generated by components/compte-formateur/exampleData.ts
// (même FIRST_NAMES, même répartition par groupe) pour que la démo Planning
// (grilles de notation, encore en state frontend local) et les vraies
// séances plantées ici pointent vers les mêmes apprenants. Emails
// fabriqués (@exemple.e-staf.mg) — pas de vraies adresses tant que le vrai
// système d'inscription n'existe pas (module 7 de la roadmap).
//
// Complété le 2026-09-15 : diagnostic initial (test d'admission), séances
// programmées, présences et notations — pour que le Compte Apprenant (voir
// NotationService.getApprenantDashboard) affiche de vraies données dès le
// seed plutôt qu'un tableau de bord entièrement vide.
const prisma = new PrismaClient();

const FIRST_NAMES = [
  "Fara", "Njaka", "Tiana", "Mihaja", "Vola", "Hasina", "Naina", "Rindra",
  "Andry", "Soa", "Lova", "Tojo", "Miora", "Fanja", "Zo", "Tahina", "Anja",
  "Feno", "Kanto", "Dera", "Manda", "Tsiory", "Iavo", "Rado", "Sitraka",
  "Onja", "Havana", "Ony", "Mamy", "Zanaka",
];

const GROUP_KEYS = ["A", "B", "C", "D", "E", "F"];
const APPRENANTS_PAR_GROUPE = 5;

// Compétences suivies séance après séance (voir
// components/compte-formateur/gradingGrids.ts, COMPETENCY_DEFS) — clés
// dupliquées ici comme dans NotationService, convention du projet.
const COMPETENCY_KEYS = [
  "comprehension_orale",
  "expression_orale",
  "comprehension_ecrite",
  "expression_ecrite",
  "posture_eloquence",
];

const COMMENTAIRES_DEMO = [
  "Bonne progression ce mois-ci, continuez sur cette lancée.",
  "Attention aux temps verbaux à l'écrit — à retravailler avant la prochaine séance.",
  "Très bonne participation à l'oral, la confiance s'installe.",
  "Le vocabulaire professionnel progresse bien, encore un effort sur la fluidité.",
  "Séance solide, quelques hésitations à l'oral mais rien d'inquiétant.",
];

const JOUR_MS = 24 * 60 * 60 * 1000;

async function main() {
  const formateurMatricule = process.env.FORMATEUR_TEST_MATRICULE ?? "ETF-FORM-2026-0001";
  const formateurTestPassword = process.env.FORMATEUR_TEST_PASSWORD ?? "formateur-demo-2026";
  // Compte individuel (2026-09-16) — même mot de passe de démo qu'avant la
  // migration (partagé via FORMATEUR_TEST_PASSWORD), pour ne pas casser le
  // login de démo existant. update: {} volontairement laissé sans password
  // pour ne pas écraser un vrai mot de passe déjà régénéré par la RH sur un
  // environnement où ce seed est rejoué.
  await prisma.formateur.upsert({
    where: { matricule: formateurMatricule },
    update: {},
    create: {
      matricule: formateurMatricule,
      prenom: "Ravaka",
      nom: "Formateur",
      email: "formateur.demo@exemple.e-staf.mg",
      password: await bcrypt.hash(formateurTestPassword, 10),
    },
  });

  const apprenantTestMatricule = process.env.APPRENANT_TEST_MATRICULE ?? "ETF-2026-0001";
  const apprenantTestPassword = process.env.APPRENANT_TEST_PASSWORD ?? "apprenant-demo-2026";
  // Tous les apprenants seedés partagent ce mot de passe (démo uniquement —
  // les vrais apprenants créés via le pipeline post-test reçoivent chacun
  // un mot de passe généré individuellement, voir EvaluationService.confirmPayment).
  const demoPasswordHash = await bcrypt.hash(apprenantTestPassword, 10);

  const now = Date.now();

  for (const [gi, cle] of GROUP_KEYS.entries()) {
    const groupe = await prisma.groupe.upsert({
      where: { cle },
      update: {},
      create: { cle, label: `Groupe ${cle}` },
    });

    // 12 séances par groupe — les 4 premières déjà passées (échelonnées sur
    // les 4 dernières semaines), la 5e programmée dans 3 jours ("prochaine
    // séance"), les suivantes pas encore planifiées par le formateur.
    const seances = await Promise.all(
      Array.from({ length: 12 }, (_, i) => i + 1).map((numero) => {
        const startAt =
          numero <= 4
            ? new Date(now - (5 - numero) * 7 * JOUR_MS)
            : numero === 5
              ? new Date(now + 3 * JOUR_MS)
              : null;
        const objectifs = numero <= 5 ? `Séance ${numero} — ${groupe.label}` : null;
        return prisma.seance.upsert({
          where: { groupeId_numero: { groupeId: groupe.id, numero } },
          update: { startAt, objectifs },
          create: { groupeId: groupe.id, numero, startAt, objectifs },
        });
      })
    );
    const seancesPassees = seances.filter((s) => s.numero <= 4);

    for (let i = 0; i < APPRENANTS_PAR_GROUPE; i++) {
      const index = gi * APPRENANTS_PAR_GROUPE + i;
      const prenom = FIRST_NAMES[index % FIRST_NAMES.length];
      const nomInitiale = String.fromCharCode(65 + (index % 26));
      // Le premier apprenant du Groupe A reprend le matricule de test réel,
      // pour que le login stopgap se résolve vers une vraie ligne Apprenant.
      const matricule = index === 0 ? apprenantTestMatricule : `ETF-2026-${String(index + 1).padStart(4, "0")}`;
      const email = `${prenom.toLowerCase()}.${index + 1}@exemple.e-staf.mg`;
      const nom = `${nomInitiale}.`;

      const apprenant = await prisma.apprenant.upsert({
        where: { matricule },
        update: { groupeId: groupe.id, password: demoPasswordHash },
        create: {
          matricule,
          prenom,
          nom,
          email,
          groupeId: groupe.id,
          password: demoPasswordHash,
          createdAt: new Date(now - 90 * JOUR_MS),
        },
      });

      // ---- Diagnostic initial (test d'admission) ---------------------
      // Un Candidat + EvaluationAttempt par apprenant, variés mais
      // déterministes (reproductible d'un seed à l'autre), pour que
      // ProfileHeader affiche un vrai diagnostic plutôt qu'un état vide.
      const lexiqueScore = 10 + (index % 8);
      const oralScore = 11 + (index % 7);
      const situationsScore = 9 + (index % 9);
      const videoScore = 10 + ((index * 3) % 8);
      const essayScore = 8 + ((index * 2) % 10);
      const totalScore = computeTotalScore([
        lexiqueScore,
        oralScore,
        situationsScore,
        videoScore,
        essayScore,
      ]);
      const tier = totalScore !== null ? computeTier(totalScore) : null;

      const existingAttempt = await prisma.evaluationAttempt.findUnique({
        where: { apprenantId: apprenant.id },
      });
      if (!existingAttempt) {
        const candidat = await prisma.candidat.create({
          data: {
            firstName: prenom,
            lastName: nom,
            email,
            phone: `0341234${String(index).padStart(3, "0")}`,
            createdAt: new Date(now - 95 * JOUR_MS),
          },
        });
        await prisma.evaluationAttempt.create({
          data: {
            candidatId: candidat.id,
            status: "active",
            lexiqueScore,
            oralScore,
            situationsScore,
            videoScore,
            essayScore,
            totalScore,
            tier,
            submittedAt: new Date(now - 93 * JOUR_MS),
            gradedAt: new Date(now - 92 * JOUR_MS),
            paymentConfirmedAt: new Date(now - 90 * JOUR_MS),
            apprenantId: apprenant.id,
          },
        });
      }

      // ---- Présences aux séances déjà passées -------------------------
      // Réparties déterministiquement : 1 absence et 1 retard sur les 4
      // séances passées, le reste à l'heure — assez de variété pour que
      // l'assiduité affichée ne soit jamais uniformément parfaite.
      for (const seance of seancesPassees) {
        const cle = (i + seance.numero) % 5;
        if (cle === 0) continue; // absence : pas de ligne Presence
        const retardMinutes = cle === 1 ? 15 : 2;
        await prisma.presence.upsert({
          where: { dailyParticipantId: `seed-${apprenant.id}-${seance.id}` },
          update: {},
          create: {
            seanceId: seance.id,
            apprenantId: apprenant.id,
            role: "apprenant",
            dailyParticipantId: `seed-${apprenant.id}-${seance.id}`,
            joinedAt: new Date(seance.startAt!.getTime() + retardMinutes * 60 * 1000),
            leftAt: new Date(seance.startAt!.getTime() + 90 * 60 * 1000),
            dureeSecondes: (90 - retardMinutes) * 60,
          },
        });
      }

      // ---- Notations sur les séances déjà passées ---------------------
      // Un commentaire seulement sur la dernière séance passée (évite 600
      // commentaires identiques) — gradé le jour même pour retomber dans le
      // "cumul du mois" du tableau de bord apprenant.
      await Promise.all(
        seancesPassees.flatMap((seance) =>
          COMPETENCY_KEYS.map((competence, ci) => {
            const scoreOn20 = 8 + ((index + seance.numero * 2 + ci) % 10);
            const estDerniereSeance = seance.numero === seancesPassees.length;
            const commentaires =
              estDerniereSeance && competence === "expression_ecrite"
                ? COMMENTAIRES_DEMO[index % COMMENTAIRES_DEMO.length]
                : null;
            const gradedAt = estDerniereSeance
              ? new Date(now - 2 * 60 * 60 * 1000)
              : new Date(seance.startAt!.getTime() + JOUR_MS);
            return prisma.notation.upsert({
              where: {
                seanceId_apprenantId_competence: {
                  seanceId: seance.id,
                  apprenantId: apprenant.id,
                  competence,
                },
              },
              update: {},
              create: {
                seanceId: seance.id,
                apprenantId: apprenant.id,
                competence,
                scoreOn20,
                commentaires,
                gradedAt,
              },
            });
          })
        )
      );
    }
  }

  console.log(
    "Seed terminé : 6 groupes, 30 apprenants (+ diagnostic initial), 1 formateur, 72 séances (5 programmées), présences et notations sur les 4 premières séances de chaque groupe."
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
