import { PrismaClient } from "@prisma/client";

// Seed de démo pour Groupe/Formateur/Apprenant — mirrors the exact 6 groupes
// / 30 apprenants generated by components/compte-formateur/exampleData.ts
// (même FIRST_NAMES, même répartition par groupe) pour que la démo Planning
// (grilles de notation, encore en state frontend local) et les vraies
// séances plantées ici pointent vers les mêmes apprenants. Emails
// fabriqués (@exemple.e-staf.mg) — pas de vraies adresses tant que le vrai
// système d'inscription n'existe pas (module 7 de la roadmap).
const prisma = new PrismaClient();

const FIRST_NAMES = [
  "Fara", "Njaka", "Tiana", "Mihaja", "Vola", "Hasina", "Naina", "Rindra",
  "Andry", "Soa", "Lova", "Tojo", "Miora", "Fanja", "Zo", "Tahina", "Anja",
  "Feno", "Kanto", "Dera", "Manda", "Tsiory", "Iavo", "Rado", "Sitraka",
  "Onja", "Havana", "Ony", "Mamy", "Zanaka",
];

const GROUP_KEYS = ["A", "B", "C", "D", "E", "F"];
const APPRENANTS_PAR_GROUPE = 5;

async function main() {
  const formateurMatricule = process.env.FORMATEUR_TEST_MATRICULE ?? "ETF-FORM-2026-0001";
  await prisma.formateur.upsert({
    where: { matricule: formateurMatricule },
    update: {},
    create: {
      matricule: formateurMatricule,
      prenom: "Ravaka",
      nom: "Formateur",
      email: "formateur.demo@exemple.e-staf.mg",
    },
  });

  const apprenantTestMatricule = process.env.APPRENANT_TEST_MATRICULE ?? "ETF-2026-0001";

  for (const [gi, cle] of GROUP_KEYS.entries()) {
    const groupe = await prisma.groupe.upsert({
      where: { cle },
      update: {},
      create: { cle, label: `Groupe ${cle}` },
    });

    for (let i = 0; i < APPRENANTS_PAR_GROUPE; i++) {
      const index = gi * APPRENANTS_PAR_GROUPE + i;
      const prenom = FIRST_NAMES[index % FIRST_NAMES.length];
      const nomInitiale = String.fromCharCode(65 + (index % 26));
      // Le premier apprenant du Groupe A reprend le matricule de test réel,
      // pour que le login stopgap se résolve vers une vraie ligne Apprenant.
      const matricule = index === 0 ? apprenantTestMatricule : `ETF-2026-${String(index + 1).padStart(4, "0")}`;

      await prisma.apprenant.upsert({
        where: { matricule },
        update: { groupeId: groupe.id },
        create: {
          matricule,
          prenom,
          nom: `${nomInitiale}.`,
          email: `${prenom.toLowerCase()}.${index + 1}@exemple.e-staf.mg`,
          groupeId: groupe.id,
        },
      });
    }

    // 12 séances par groupe (numéro 1-12), sans horaire par défaut — le
    // formateur les planifie depuis Planning par Groupe.
    for (let numero = 1; numero <= 12; numero++) {
      await prisma.seance.upsert({
        where: { groupeId_numero: { groupeId: groupe.id, numero } },
        update: {},
        create: { groupeId: groupe.id, numero },
      });
    }
  }

  console.log("Seed terminé : 6 groupes, 30 apprenants, 1 formateur, 72 séances (sans horaire).");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
